// packages/react/src/types/ReachProviderProps.ts
import type { PropsWithChildren } from "react";

import type { ReachNetwork } from "src/types/ReachNetwork";

/**
 * The Reach to publish, and whether the provider holds a runtime lease while
 * it is mounted, `false` by default.
 *
 * @example
 * ```tsx
 * const props: ReachProviderProps = { network: reach, start: true };
 * ```
 */
export type ReachProviderProps = PropsWithChildren<{
  network: ReachNetwork;
  start?: boolean;
}>;

// packages/solid/src/types/ReachProviderProps.ts
import type { ParentProps } from "solid-js";

import type { ReachNetwork } from "src/types/ReachNetwork";

/**
 * The Reach to publish, and whether the provider holds a runtime lease while
 * it is mounted, `false` by default.
 *
 * @example
 * ```ts
 * const props: ReachProviderProps = { network: reach, start: true };
 * ```
 */
export type ReachProviderProps = ParentProps<{
  network: ReachNetwork;
  start?: boolean;
}>;
